### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by edsondc** [Raman-Maan/cinder#105]
# Submittables
- [ ] Project Report (10-20 pages, double spaced, due on April 13).
- [x] Presentation (March 27)

# Documentation
- [x] Update README's.
- [ ] Update the Architecture Page in the Wiki.
- [ ] Update the Domain Model Page in the Wiki.
- [ ] Update the Database Page in the Wiki.

# Testing
- [x] System Tests: Web
- [x] System Tests: Mobile

# Application
- [x] Profile [#11, #13]
- [x] Signup [#11, #13]
- [x] Age Filter [#68]
- [x] Gender Filter [#76]
- [ ] Education Filter [#71]
- [ ] Religion Filter [#70]
- [ ] Interests Filter [#75]
