### ISSUE TITLE
As a new user, I want to be able to create a profile

### ISSUE THREAD

**Issue by Raman-Maan** [Raman-Maan/cinder#11]
EPIC #2 
---
_Cost:_ 3 days

## Tasks
- [x] _11.1_ [WEB] Build account creation page [@imaple7] [PR #57]
- [x] _11.2_ [BACKEND] Add endpoint to GET/POST user info+filter [@edsondc]
- [x] _11.3_ [WEB] Add form validation to account creation page
- [ ] _11.4_ [MOBILE] Build account creation page
- [ ] _11.5_ [MOBILE] Add form validation to account creation page
- [x] _11.6_ [BACKEND] Create, Get, Save User in the Database [@edsondc] [PR #110 ]
- [x] _11.8_ [MOBILE] Create a landing for the user's profile page [@hellothisisMatt] [PR #78]
- [x] _11.9_ [WEB] Connect signup page with its endpoint [@minblake]
- [x] _11.10_ [WEB] Add Signup endpoint [@minblake]
