### ISSUE TITLE
As a user, I want to be able to log into my account

### ISSUE THREAD

**Issue by Raman-Maan** [Raman-Maan/cinder#13]
EPIC #2 
---
_Cost:_ 1 day

## Tasks
- [x] _13.1_ __Build *web* login page__ [@Raman-Maan] [PR #28]
- [x] _13.2_ __Configure endpoints to accept user login details and authenticate__ [@minblake]
- [x] _13.3_ __Maintain logged in user through *web* interaction__ [@minblake]
- [x] _13.4_ __Build *mobile* login page__ [@Raman-Maan] [PR #36]
- [ ] _13.5_ __Maintain logged in user through *mobile* session__
- [ ] _13.6_ __Add form validation for login to web client__
- [ ] _13.7_ __Add form validation for login to mobile client__
- [x] _13.8_ __[WEB] Add logout functionality__
- [ ] _13.9_ __[MOBILE] Add logout button__
