### ISSUE TITLE
As a user, I want to be able to add a picture of myself to my profile

### ISSUE THREAD

**Issue by Raman-Maan** [Raman-Maan/cinder#14]
EPIC #2 
---
_Cost:_ 1 day

## Tasks
- [ ] _14.1_ [WEB] Allow user to upload a picture of themselves during sign up [@hellothisisMatt]
- [ ] _14.2_ [MOBILE] Allow user to upload a picture of themselves during sign up
- [ ] _14.3_ Save picture during sign up into server, add to user
- [ ] _14.4_ Compress & mutate images before saving into server
- [ ] _14.5_ [WEB] Allow existing user to upload a picture of themselves
- [ ] _14.6_ [MOBILE] Allow existing user to upload a picture of themselves during sign up
