### ISSUE TITLE
As a user, I want to have a home screen

### ISSUE THREAD

**Issue by RamanMaan** [Raman-Maan/cinder#30]
EPIC #4
---
_Cost:_ 1 day

## Tasks
- [x] _30.1_ [WEB] Build a landing page with user details displayed [@hellothisisMatt]
- _30.2_ ~[MOBILE] Build a landing page with user details displayed~
- [x] _30.3_ [WEB] Add a navigation bar to navigate home screen and other screens [@hellothisisMatt]
- [x] _30.4_ [MOBILE] Add a navigation bar to navigate [@Raman-Maan] [PR #65]
