### ISSUE TITLE
As a user, I want to see all my matches

### ISSUE THREAD

**Issue by RamanMaan** [Raman-Maan/cinder#31]
EPIC #4
---
_Cost:_ 2-3 days

## Tasks
- [x] _31.1_ [WEB] Build a matches page displaying all user matches [@Raman-Maan] [PR #37]
- [x] _31.2_ [MOBILE] Build a matches page displaying all user matches [@edsondc] [PR #66]
- [x] _31.3_ Add endpoint to get all of the users matches [@edsondc] [PR #39]
- [x] _31.4_ [WEB] Add matches page to home page
- ~_31.5_ [MOBILE] Add matches page to navigation~
- [x] _31.6_ Integrate endpoint to matches page [@Raman-Maan] [PR #42]
