### ISSUE TITLE
As a user, I want to be able to view my matches details

### ISSUE THREAD

**Issue by RamanMaan** [Raman-Maan/cinder#32]
EPIC #4
---
_Cost:_ 1-2 days

## Tasks
- [x] _32.1_ [WEB] Build a match details component to display the matches name, age, and contact info [@imaple7] [PR #38] [PR #50]
- [x] _32.2_ [MOBILE] Build a match details component to display the matches name, age, and contact info [@kevnis] [PR #83]
- [x] _32.3_ Add endpoint to get matches details [@minblake] [PR #51]
- [x] _32.4_ [WEB] Integrate matches component to matches page[@imaple7] [PR #40]
- [x] _32.5_ [MOBILE] Integrate matches component to matches page [@Raman-Maan] [PR #85]
