### ISSUE TITLE
As a user I want to be able to see potential matches

### ISSUE THREAD

**Issue by RamanMaan** [Raman-Maan/cinder#33]
EPIC #8
---
_Cost:_ 1-2 days

## Tasks
- [x] _33.1_ [WEB] Build a finding match page to display potential matches [@kevnis]
- [x] _33.2_ [MOBILE] Build a recommend page to display recommendations [@Raman-Maan] [PR #67]
- [x] _33.3_ Add endpoint to get potential matches [@Raman-Maan] [PR #41]
- [x] _33.4_ [MOBILE] Connect endpoint to displaying potential matches page [@Raman-Maan] [PR #77]
