### ISSUE TITLE
As a user, I want to be able to approve/reject a potential match

### ISSUE THREAD

**Issue by RamanMaan** [Raman-Maan/cinder#34]
EPIC #8
---
_Cost:_ 1-2 days

## Tasks
- [x] _34.1_ Add endpoint to handle approve/reject [@imaple7] [PR #49 ]
- [x] _34.2_ [WEB] After approve/reject, bring up next potential match [@kevnis]
- ~_34.3_ [MOBILE] After approve/reject, bring up next potential match~ Already done
- ~_34.4_ [WEB] Add swiping to approve/reject~ Will be done later as a nice to have
- ~_34.5_ [MOBILE] Add swiping to approve/reject~ Already done
- [x] _34.6_ [WEB] Connect endpoint to approve/reject in ui (_34.2_) [@kevnis]
- [x] _34.7_ [MOBILE] Connect approve/reject to endpoint [@Raman-Maan] [PR #79]
