### ISSUE TITLE
Cleanup Tasks

### ISSUE THREAD

**Issue by RamanMaan** [Raman-Maan/cinder#35]
- [x] Add a build script to initialize database [@Raman-Maan] [PR #45]
- [x] Add a build script to add test data to database [@Raman-Maan] [PR #45]
- [x] Add a build script to add init prod data to database [@Raman-Maan] [PR #56]
- [x] Tie scripts together to prep database [@Raman-Maan] [PR #45]
- [x] Updated manifest from React App to cinder [@Raman-Maan] [PR #45]
- [x] Better test data [@Raman-Maan] [PR #56]
