### ISSUE TITLE
As a user, I want to be able to filter by age

### ISSUE THREAD

**Issue by mgopez** [Raman-Maan/cinder#68]
EPIC #5
---
I want to be able to filter my recommendations by an age range, from some minimum to some maximum. I want both of these fields to be optional i.e. I can set a minimum or maximum value, or both.

_Cost:_ 2-3 days

## Tasks
- [x] _68.1_ [WEB] Add to user profile a filter element with two options: one for a minimum age, one for a maximum age. [@imaple7] [PR #117]
- [x] _68.2_ [MOBILE] Add to user profile a filter element with two options: one for a minimum age, one for a maximum age. [@imaple7] [PR #124]
- [x] _68.5_ [BACKEND] Filter user recommendations by age if they have an age filter [@imaple7] [PR #97]
