### ISSUE TITLE
As a user, I want to be able to filter by religion

### ISSUE THREAD

**Issue by hellothisisMatt** [Raman-Maan/cinder#70]
EPIC #5
---
I want to be able to select predefined religions as religions I want my recommendations to follow. The religions should be the same options that I was able to choose mine from. This should be done as a multi-select dropdown because I might be willing to accept multiple different religions.

_Cost:_ 1-2 days

## Tasks
- [ ] _70.1_ [WEB] In users profile settings, add a filter element to with a multi-select dropdown to choose religions I'm interested in.
- [ ] _70.2_ [MOBILE] In users profile settings, add a filter element to with a multi-select dropdown to choose religions I'm interested in.
- [ ] _70.3_ [BACKEND] Link these dropdowns to get their values from the API. Configure endpoint to get religion reference table data.
- [ ] _70.4_ [BACKEND] Filter users recommendations by religion if a religion filter is present
- [ ] _70.5_ [BACKEND] Update user filter to get and save religion filter
