### ISSUE TITLE
As a user, I want to be able to filter by education

### ISSUE THREAD

**Issue by hellothisisMatt** [Raman-Maan/cinder#71]
EPIC #5
---
I want to be able to filter my recommendations by their education level.

_Cost:_ 1-2 days

## Tasks
- [ ] _71.1_ [WEB] In users profile settings, add a filter element to with a multi-select dropdown to choose educations I'm interested in.
- [ ] _71.2_ [MOBILE] In users profile settings, add a filter element to with a multi-select dropdown to choose educations I'm interested in.
- [x] _71.3_ [BACKEND] Link these dropdowns to get their values from the API. Configure endpoint to get education reference table data. [@edsondc][PR #106]
- [ ] _71.4_ [BACKEND] Filter users recommendations by education if a education filter is present
- [ ] _71.5_ [BACKEND] Update user filter to get and save education filter [@edsondc]
