### ISSUE TITLE
As a user, I want to be able to set filters once and keep them

### ISSUE THREAD

**Issue by hellothisisMatt** [Raman-Maan/cinder#72]
EPIC #5
---
I want to be able to set my filters in my profile, and have them be saved. So if I set my filters on the app, it should also apply to profile on the web client, and vice-versa. If I close the app and reopen it my filters are still there.

We will allow filter 'updates' by simply replacing a users filters everytime new filters are submitted. i.e. We delete the users old filters and store the new ones. 

_Cost:_ 1-2 days

### Tasks

- [x] _72.1_ [BACKEND] Configure endpoints to accept users (new) filters, and get users filters [@imaple7][PR #94]
- [x] _72.2_ [DB] Store users filters in database [@edsondc] [PR #92]
    - This is the general filter object - for now we will only concern ourselves with Age and Gender
- [x] _72.3_ [WEB] Display users existing filters in their profile page [@Raman-Maan] [PR #129]
- [ ] _72.4_ [MOBILE] Display users existing filters in their profile page
