### ISSUE TITLE
As a user, I want to be able to filter by location

### ISSUE THREAD

**Issue by mgopez** [Raman-Maan/cinder#73]
EPIC #5
---

I want to be able to filter by my **current** location. 

We should allow filtering to a minimum value of say 50km, and lets say the input range increments by 10km each time. We will only support km as the unit of measurement. You could implement this as a slider for a range, or a numerical input range element. 

_Cost:_ 1-2 days

### Tasks

- [ ] _73.1_ [WEB] In users profile settings, add a filter element with a input range to a max distance I'm willing to match to. 
- [ ] _73.2_ [MOBILE] In users profile settings, add a filter element with a input range to a max distance I'm willing to match to. 
- [ ] _73.3_ [BACKEND] Filter users recommendations by location if a location filter is present
- [ ] _73.4_ [BACKEND] Update user filter to save location filter
