### ISSUE TITLE
As a user, I want to be able to filter by age [DUPLICATE]

### ISSUE THREAD

**Issue by mgopez** [Raman-Maan/cinder#74]
EPIC #5
---
I want to be able to filter my recommendations by an age range, from some minimum to some maximum. I want both of these fields to be optional i.e. I can set a minimum or maximum value, or both.

_Cost:_ 2-3 days

## Tasks
- [ ] _74.1_ [WEB] Add to user profile a filter element with two options: one for a minimum age, one for a maximum age.
- [ ] _74.2_ [MOBILE] Add to user profile a filter element with two options: one for a minimum age, one for a maximum age.
- [ ] _74.3_ [BACKEND] Filter user recommendations by age if they have an age filter
