### ISSUE TITLE
As a user, I want to be able to filter on interests

### ISSUE THREAD

**Issue by hellothisisMatt** [Raman-Maan/cinder#75]
EPIC #5
---

I want to be able to filter on mutual interests. This should display recommendations that have at least one interest that I also share.

_Cost:_ 3-4 days

## Tasks
- [ ] _75.1_ [WEB] Add a filter field which is just a toggle to turn filtering by interests on/off
- [ ] _75.2_ [MOBILE] Add a filter field which is just a toggle to turn filtering by interests on/off
- [ ] _75.3_ [BACKEND] Link these dropdowns to get their values from the API. Configure endpoint to get interest reference table data.
- [ ] _75.4_ [BACKEND] Filter recommendations by interests if user has interest filter
- [ ] _75.5_ [BACKEND] Update user filter to get and save interest filter
