### ISSUE TITLE
As a user, I want to be able to filter by gender

### ISSUE THREAD

**Issue by mgopez** [Raman-Maan/cinder#76]
EPIC #5
---

I want to be able to filter my recommendations based on their gender.

_Cost:_ 1-2 days

## Tasks
- [x] _76.1_ [WEB] In users profile settings, add a filter element to with a multi-select dropdown to choose genders I'm interested in. [@Raman-Maan] [PR #91]
- [x] _76.2_ [MOBILE] In users profile settings, add a filter element to with a multi-select dropdown to choose genders I'm interested in. [@Raman-Maan]
- [x] _76.3_ [BACKEND] Configure endpoint to get gender reference table data. [@imaple7] [PR #84]
- [x] _76.4_ [BACKEND] Filter users recommendations by gender if a gender filter is present [@imaple7] [PR #96]
~_76.5_ Integrate filter element with backend [@Raman-Maan]~
