### ISSUE TITLE
Create backend tests

### ISSUE THREAD

**Issue by minblake** [Raman-Maan/cinder#81]
### Setup
- [x] _81.1_ Initial Setup (Install Jest into the server project as a dev dependency). [@edsondc][PR #98]

### Database API Tests
- [x] _81.2_ Create Tests for Matches Database API. [@edsondc][PR #99]
- [x] _81.3_ Create Tests for Recommendations Database API. [@edsondc][PR #100]
- [x] _81.4_ Create Tests for Filters Database API. [@edsondc][PR #101]
- [x] _81.5_ Create Tests for References Database API. [@edsondc][PR #102]
