### ISSUE TITLE
Create acceptance tests 

### ISSUE THREAD

**Issue by kevnis** [Raman-Maan/cinder#88]
Create acceptance tests using CodeceptJS + WebdriverIO

## Tasks
- [x] _88.1_ [WEB] Initial Setup - Adding CodeceptJS and Webdriver for web acceptance tests [@kevnis]
- [x] _88.2_ [MOBILE] Initial Setup - Adding CodeceptJS and Appium for mobile acceptance tests [@hellothisisMatt]
- [x] _88.3_ [WEB] Write tests for approving/rejecting a recommended user [@kevnis]
- [x] _88.4_ [MOBILE] Write tests for approving/rejecting a recommended user [@hellothisisMatt]
- [x] _88.5_ [WEB] Write tests for viewing match details [@kevnis]
- [x] _88.6_ [MOBILE] Write test for viewing match details [@hellothisisMatt]
- [x] _88.7_ [WEB] Write test for viewing profile [@kevnis]
- [x] _88.8_ [MOBILE] Write test for viewing profile [@hellothisisMatt]
- [x] _88.9_ [WEB] Update .travis.yml file + add scripts for running system tests [@kevnis]
